app/urls.py
"""
Definition of urls for mysite.
"""

from django.urls import path
from app import views

app_name = 'app'
urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
]

mysite/urls.py
"""
Definition of urls for mysite.
"""

from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('accounts.urls')),
    path('news/', include('news.urls')),
    path('streams/', include('streams.urls')),
    path('discordTool/', include('discordTool.urls')),
]

news/urls.py
from django.urls import path
from news.views import scrape, news_list

app_name = 'news'
urlpatterns = [
	path('scrape/', scrape, name="scrape"),
	path('', news_list, name="home"),
]

news/models.py
from django.conf import settings
from django.db import models
import datetime

# Create your models here.

# Scrape data coming from websites
# The posts will contain images, urls and titles

# model - headline(title, image, url)

# model - userprofile(user, last_scrape)

class Headline(models.Model):
	title = models.CharField(max_length=200)
	image = models.URLField(null=True, blank=True)
	url = models.TextField()
	date = models.TextField()

	def __str__(self):
		return self.title

news/views.py
import requests
from django.shortcuts import render, redirect
from bs4 import BeautifulSoup as BSoup
from news.models import Headline
import time, datetime

requests.packages.urllib3.disable_warnings()

def news_list(request):
    headlines = Headline.objects.all()[::-1]

    return render(request, "news/home.html", {
		'object_list': headlines,
	})


def scrape(request):
    session = requests.Session()
    session.headers = {"User-Agent": "Googlebot/2.1 (+http://www.google.com/bot.html)%22%7D"}
    url = "https://www.ynet.co.il/home/0,7340,L-8,00.html"

    content = session.get(url, verify=False).content
    soup = BSoup(content, "html.parser")
    News = soup.find_all('div', {"class":"str3s str3s_small str3s_type_small"})
    Titles = soup.find_all('div',{"class":"title"})
    TitlesText = []
    for title in Titles:
        t = title.text
        TitlesText.append(t)

    i = 0
    new_headline_links = []
    for article in Headline.objects.all():
        new_headline_links.append(article.title)


    for artcile in News:
        main = artcile.find_all('a')[0]

        link = main['href']
        image_src = str(main.find('img')['src']).split(" ")[0]

        if (TitlesText[i] in new_headline_links):
            break

        if (link.find("https") != -1):
            link2 = link
        else:
            link2 = "https://www.ynet.co.il/"+link

        link2 = link2.replace('#autoplay','')
        articleContent = session.get(link2, verify=False).content
        print(link2)
        soup = BSoup(articleContent, "html.parser")

        new_headline = Headline()


        ok = "פורסם:"
        #header = soup.find_all('div', {"class":"element B3 ghcite noBottomPadding"})[0]
        dates = soup.find_all('span', string=ok)
        print(dates)


        new_headline.date = dates[1].text
        new_headline.title = TitlesText[i]
        new_headline.url = link2
        new_headline.image = image_src
        #if (new_headline.date != 'error#'):
        #    new_headline.save()
        new_headline.save()
        i = i + 1


    return redirect("../")

news/templates/news/home.html
{% extends "app/layout.html" %}

{% block content %}

<!DOCTYPE html>
<html>

<body>
	<div class="jumbotron">
		<h1>News from Ynet</h1>
		<form method="POST" action="{% url 'news:scrape' %}">
			{% csrf_token %}
			<button type="submit" class="btn btn-success">Get news</button>
		</form>
	</div>
<ul class="article">
	{% for object in object_list %}
	<li>
		<div class="card" style="height: 20rem;width: 20rem;border:5px black solid;">
	  <img class="card-img-top" src = "{{ object.image }}" width="189" height="105.6">

	  <div class="card-body">
		<h5 class="card-title"><div>
		  <a href="{{object.url}}"><h5 class="card-title">{{object.title}} <br> {{object.date}}</h5></a>

		</div>
		</div>
	  </div>
	</li>	
	{% endfor %}
</ul>

	<script
	src="http://code.jquery.com/jquery-3.3.1.min.js"
	integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
	crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>
<style>
	.article {
  list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
  background-color: #333;
}

li {
  float: left;
}

	li a {
		display: block;
		color: white;
		text-align: center;
		padding: 14px 16px;
		text-decoration: none;
	}

li a:hover {
  background-color: #111;
}
</style>

{% endblock %}