accounts/urls.py
from datetime import datetime
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from app import forms
from accounts import views
from django.conf import settings

app_name = 'accounts'
urlpatterns = [
    path('login/',
         LoginView.as_view
         (
             template_name='accounts/login.html',
             authentication_form=forms.BootstrapAuthenticationForm,
             extra_context=
             {
                 'title': 'Log in',
                 'year' : datetime.now().year,
             }
         ),
         name='login'),
    path('logout/', LogoutView.as_view(next_page=(settings.LOGOUT_REDIRECT_URL)), name='logout'),
    path('signup/', views.signup, name='signup'),
    ]

app/urls.py
"""
Definition of urls for mysite.
"""

from django.urls import path
from app import views

app_name = 'app'
urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
]

mysite/urls.py
"""
Definition of urls for mysite.
"""

from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('accounts.urls')),
    path('news/', include('news.urls')),
    path('streams/', include('streams.urls')),
    path('discordTool/', include('discordTool.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.views import LoginView
from app import forms

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
             form.save()
             new_user = authenticate(username=form.cleaned_data['username'],
                                    password=form.cleaned_data['password1'],)
             login(request, new_user)
             return HttpResponseRedirect('/')
        # log the user in
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})

accounts/templates/accounts/login.html
{% extends "app/layout.html" %}
{% load static %}

{% block content %}

<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Use a local account to log in.</h4>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">User name</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Password</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Log in" class="btn btn-default" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Please enter a correct user name and password.</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

accounts/templates/accounts/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="../accounts/logout/" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">Hello {{ user.username }}!</span></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
    </ul>
</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'accounts:login' %}">Log in</a></li>
</ul>

{% endif %}

accounts/templates/accounts/signup.html
{% extends "app/layout.html" %}

{% block content %}

<form class="form-horizontal" method="post">
    {% csrf_token %}
    {{ form }}
    <br />
    <input type="submit" value="Sign up" class="btn btn-default" />
</form>

{% endblock %}

accounts/templates/accounts/signuppartial.html
{% if user.is_authenticated %}

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
</ul>

{% endif %}