app/urls.py
"""
Definition of urls for mysite.
"""

from django.urls import path
from app import views

app_name = 'app'
urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
]

discordTool/urls.py
from django.urls import path
from discordTool.views import members_list

app_name = 'discordTool'
urlpatterns = [
	path('', members_list, name="home"),
]

mysite/urls.py
"""
Definition of urls for mysite.
"""

from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('accounts.urls')),
    path('news/', include('news.urls')),
    path('streams/', include('streams.urls')),
    path('discordTool/', include('discordTool.urls')),
]

news/urls.py
from django.urls import path
from news.views import scrape, news_list

app_name = 'news'
urlpatterns = [
	path('scrape/', scrape, name="scrape"),
	path('', news_list, name="home"),
]

streams/urls.py
from django.urls import path
from streams import views

app_name = 'streams'
urlpatterns = [
	path('choice/', views.choice, name='choice'),
	path('stream/<str:chosen_stream>/', views.stream, name='stream'),
]

app/templates/app/about.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<p>Use this area to provide additional information.</p>

{% endblock %}

app/templates/app/contact.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

{% endblock %}

app/templates/app/index.html
{% extends "app/layout.html" %}

{% block content %}

<p>ok</p>
{% endblock %}

app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Neta's Site</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">Neta's Site</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'app:home' %}">Home</a></li>
                    <li><a href="{% url 'app:about' %}">About</a></li>
                    <li><a href="{% url 'app:contact' %}">Contact</a></li>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'news:home'%}">News</a></li>
                        <li><a href="{% url 'streams:choice'%}">Live</a></li>
                        <li><a href="{% url 'discordTool:home'%}">Discord Tool</a></li>
                    {% endif %}
                </ul>
                {% include 'accounts/loginpartial.html' %}
                {% include 'accounts/signuppartial.html' %}
            </div>
        </div>
    </div>

    <div class="container body-content">
{% block content %}{% endblock %}
        <hr/>
        <footer>
            <p>&copy; {{ year }} - My Django Application</p>
        </footer>
    </div>

    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>